name: Email Notification

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - subject: Plain body (Markdown)
            convert_markdown: true
            body: file://README.md

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: ./
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: ${{matrix.subject}}
          body: ${{matrix.body}}
          html_body: ${{matrix.html_body}}
          to: ${{github.event.pusher.email}}
          from: github-actions
          attachments: ${{matrix.attachments}}
          convert_markdown: ${{matrix.convert_markdown}}
          priority: high
