name: Email Notification

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Todo
        run: |
          python update_todo.py

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: "Todo for ${{steps.date.outputs.today}}"
          body: ${{matrix.body}}
          html_body: file://todos/${{steps.date.outputs.today}}.md
          to: yangyang.li@northwestern.edu
          from: TODAY-TODO-LIST
          attachments: ""
          convert_markdown: true
          priority: high

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git add .
          git commit -m "update todos" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
